# Generated by Django 5.1.2 on 2024-10-14 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField(choices=[(1, 'Buy'), (-1, 'Sell')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('remaining_quantity', models.IntegerField()),
                ('average_traded_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_order_id', models.IntegerField()),
                ('ask_order_id', models.IntegerField()),
                ('traded_quantity', models.IntegerField()),
                ('execution_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('execution_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
